name: Keep Supabase Awake
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Keep Alive Remote Procedure
        run: |
          curl -i -X POST "https://supabase.co" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"
