name: Keep Supabase Awake
on:
  schedule:
    - cron: '0 0 */3 * *' # Automatically runs every 3 days
  workflow_dispatch: # Allows you to manually click "Run"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Insert Row to Supabase Table
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/rest/v1/keep_alive" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'
